name: Warlords
version: WL 2.0 RC-6
author: ebic
main: com.ebicep.warlords.Warlords
depend: [ MultiWorld, HolographicDisplays ]
load: POSTWORLD
commands:
  start:
    description: Starts a new game.
    usage: /start [MAP | RANDOM]
  endgame:
    description: Force stops the game.
    usage: /endgame
  menu:
    description: Opens the game menu.
    usage: /menu
  shout:
    description: Shouts in game
    usage: /shout [MESSAGE]
  hotkeymode:
    description: Switches between hotkeymode and classic
    usage: /hotkeymode
  wl:
    description: Debug tools.
    usage: /wl [args]
  class:
    description: Select your class.
    usage: /class [class]
